@BASE_URL = http://localhost:8080

# @name read_tasks
GET {{BASE_URL}}/tasks

### 

# @name create_task
POST {{BASE_URL}}/tasks
Content-Type: application/json

{
  "title": "Learn Go",
  "description": "Learn Go in 30 minutes",
  "status": false
}

### 

# @name update_task
PUT {{BASE_URL}}/tasks/1
Content-Type: application/json

{
  "title": "Learn Go",
  "description": "Learn Go in 40 minutes",
  "status": true
}

### 

# @name delete_task
DELETE {{BASE_URL}}/tasks/1

